### ISSUE TITLE
Json serialization

### ISSUE THREAD

**Issue by vladObrazumov** [sad-spirit/pg-wrapper#11]
Hi, thanks for your library it's really helping.
i have a question, i want to json_encode a Point but i was getting an empty array, is there any other way then to set my own PointConverter and Point type. Thanks.

**Comment by sad-spirit** [comment]
Hi,
Yes, this is the only way right now, unfortunately. It definitely makes sense to add `JsonSerializable` implementation to all classes that currently implement `ArrayRepresentable`, this will allow converting to JSON and back.

**Comment by vladObrazumov** [comment]
If you find time for this improvement that would be great. Thanks. You are doing an amazing job.
