### ISSUE TITLE
NumericConverter::inputNotNull returns string

### ISSUE THREAD

**Issue by mapcentia** [sad-spirit/pg-wrapper#13]
The return type in NumericConverter::inputNotNull is string. Should it not be cast to a numeric type? Or has it something to do with the precision? 

https://github.com/sad-spirit/pg-wrapper/blob/master/src/sad_spirit/pg_wrapper/converters/NumericConverter.php#L34

**Comment by sad-spirit** [comment]
> Should it not be cast to a numeric type?

It shouldn't: Postgres has numeric type of (essentially) [unlimited precision](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL). If we convert to PHP's int or float we only have 8 bytes (4 bytes for ints on 32-bit build), also conversion to a floating point number is a loss of precision in itself.

Even IntegerConverter may return string if PHP's integer will overflow from input: https://github.com/sad-spirit/pg-wrapper/blob/master/src/sad_spirit/pg_wrapper/converters/IntegerConverter.php#L43

PHP has a [couple](https://www.php.net/manual/en/book.bc.php) of [extensions](https://www.php.net/manual/en/book.gmp.php) for arbitrary precision calculations and both of these accept strings as input anyway.
